### ISSUE TITLE
Orangetheses gem throws an error when running the rake task to generate theses

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1712]
Running `FILEPATH=/home/deploy/theses.json bin/rake orangetheses:cache_theses` in `bibdata-alma-worker1` gives the following error:

```
/opt/marc_liberation/shared/bundle/ruby/2.6.0/bundler/gems/orangetheses-2a39ca65ea90/lib/orangetheses/fetcher.rb:7: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER
** [Honeybadger] Reporting error id=75469f08-5220-4629-a12d-dead6eb1c83b level=1 pid=27435
rake aborted!
NameError: undefined local variable or method `community_id' for #<Orangetheses::Fetcher:0x000055dcade8a140>
/opt/marc_liberation/shared/bundle/ruby/2.6.0/bundler/gems/orangetheses-2a39ca65ea90/lib/orangetheses/fetcher.rb:131:in `api_collections'
/opt/marc_liberation/shared/bundle/ruby/2.6.0/bundler/gems/orangetheses-2a39ca65ea90/lib/orangetheses/fetcher.rb:138:in `api_collections_json'
/opt/marc_liberation/shared/bundle/ruby/2.6.0/bundler/gems/orangetheses-2a39ca65ea90/lib/orangetheses/fetcher.rb:143:in `collections'
/opt/marc_liberation/shared/bundle/ruby/2.6.0/bundler/gems/orangetheses-2a39ca65ea90/lib/orangetheses/fetcher.rb:70:in `cache_all_collections'
/opt/marc_liberation/shared/bundle/ruby/2.6.0/bundler/gems/orangetheses-2a39ca65ea90/lib/tasks/orangetheses.rake:20:in `block (3 levels) in <top (required)>'
/opt/marc_liberation/shared/bundle/ruby/2.6.0/bundler/gems/orangetheses-2a39ca65ea90/lib/tasks/orangetheses.rake:19:in `open'
/opt/marc_liberation/shared/bundle/ruby/2.6.0/bundler/gems/orangetheses-2a39ca65ea90/lib/tasks/orangetheses.rake:19:in `block (2 levels) in <top (required)>'
Tasks: TOP => orangetheses:cache_theses
```

The issue seems to have been introduced in https://github.com/pulibrary/orangetheses/commit/303bafe8214590e86f75ece298b7601d8b6b5a16
